### PR TITLE
added you lost game msg

### PR DESCRIPTION
**Pull request by itzROHIT-coder**

### CODE REVIEW

**Comment by itzROHIT-coder** [comment]
review @abhishek-sultaniya

**Comment by abhishek-sultaniya** [comment]
> review @abhishek-sultaniya

Good work @itzROHIT-coder 

But the game should end after message you lost.
When 1 card was left,I selected it then message came you won.

You have to do something that when you lost message comes then the 1 left card does not get selected by user.

**Comment by abhishek-sultaniya** [comment]
image

image

This may help you to understand the problem.

**Comment by itzROHIT-coder** [comment]
okay i got it

**Comment by itzROHIT-coder** [comment]
solved that problem @abhishek-sultaniya check it

**Comment by abhishek-sultaniya** [comment]
> solved that problem @abhishek-sultaniya check it

Nope,still some changes are required @itzROHIT-coder .
When I select a right card on 5th attempt its showing as a you lost game.

**Comment by itzROHIT-coder** [comment]
fixed  that @abhishek-sultaniya

**Pull request merged**
